### ISSUE TITLE
ERROR: cannot launch node of type [monitoring_monitors_system/ram_monitoring_node]: Cannot locate node of type [ram_monitoring_node] in package [monitoring_monitors_system]. Make sure file exists in package path and permission is set to executable (chmod +x)

### ISSUE THREAD

**Issue by Helge543** [luhrts/monitoring#3]
Hi, it looks like this monitoring package is also working quite well on ROS noetic/Ubuntu 20.04. However, there is just one problem (at least on my side):

I get the following error message when I compile the packages via `catkin_make`

`ERROR: cannot launch node of type [monitoring_monitors_system/ram_monitoring_node]: Cannot locate node of type [ram_monitoring_node] in package [monitoring_monitors_system]. Make sure file exists in package path and permission is set to executable (chmod +x)`

Obviously there seems to be a problem with the `ram_monitoring_node`. I've seen in the `CMakeLists.txt` that this node depends on `procps` otherwise there will be problems and it would not be built I think. I've installed libprocps via  `sudo apt-get install libprocps-dev` because I had problems trying it the way you mentioned it via `sudo apt install libprocps4-dev python-ntplib`.

Thank you for any hints!

**Comment by PanterSoft** [comment]
@Helge543 what was the problem ? I got the same issue
